spring:
  application:
    name: PATIENT-SERVICE
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/patient_service
    username: root
    password: Abhi@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}

external:
  doctor-service-base-url: ${DOCTOR_BASE_URL:http://localhost:8083}
  appointment-service-base-url: ${APPOINTMENT_BASE_URL:http://localhost:8084}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

