spring:
  application:
    name: APPOINTMENT-SERVICE
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/appointment_service
    username: root
    password: Abhi@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8084

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
  topics:
    bookRequest: appointment-book-request
    confirmed: appointment-confirmed
    rejected: appointment-rejected
    cancelled: appointment-cancelled
    notify: user-notify-request

external:
  doctor-service-base-url: ${DOCTOR_BASE_URL:http://localhost:8083}
  patient-service-base-url: ${PATIENT_BASE_URL:http://localhost:8082}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

#  Environment variables & config to set

#KAFKA_BOOTSTRAP: localhost:9092
#DOCTOR_BASE_URL: http://localhost:8083
#PATIENT_BASE_URL: http://localhost:8082
